spring:
  config:
    import: optional:classpath:application-secret.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/fx_app_db
    username: fx_app_dev
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 5076

management:
  endpoints:
    web:
      exposure:
        include: health, info
